version: '2'

services:

  orderer.shuru-network.com:
    container_name: orderer.shuru-network.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/gopath/fabric-samples/shuru-network/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/opt/gopath/fabric-samples/shuru-network/channel-artifacts/genesis.block
    - ../crypto-config/ordererOrganizations/shuru-network.com/orderers/orderer.shuru-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/shuru-network.com/orderers/orderer.shuru-network.com/tls/:/var/hyperledger/orderer/tls
    - orderer.shuru-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.shuru.shuru-network.com:
    container_name: peer0.shuru.shuru-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.shuru.shuru-network.com
      - CORE_PEER_ADDRESS=peer0.shuru.shuru-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.shuru.shuru-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shuru.shuru-network.com:7051
      - CORE_PEER_LOCALMSPID=ShuruMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shuru.shuru-network.com/peers/peer0.shuru.shuru-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shuru.shuru-network.com/peers/peer0.shuru.shuru-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.shuru.shuru-network.com:/var/hyperledger/production
    ports:

  peer0.customer.shuru-network.com:
    container_name: peer0.customer.shuru-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.customer.shuru-network.com
      - CORE_PEER_ADDRESS=peer0.customer.shuru-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customer.shuru-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customer.shuru-network.com:7051
      - CORE_PEER_LOCALMSPID=CustomerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/customer.shuru-network.com/peers/peer0.customer.shuru-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/customer.shuru-network.com/peers/peer0.customer.shuru-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.customer.shuru-network.com:/var/hyperledger/production
    ports:
      - 11051:7051d
      - 7051:7051

  

  peer0.beyond.shuru-network.com:
    container_name: peer0.beyond.shuru-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.beyond.shuru-network.com
      - CORE_PEER_ADDRESS=peer0.beyond.shuru-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.beyond.shuru-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.beyond.shuru-network.com:7051
      - CORE_PEER_LOCALMSPID=BeyondMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/beyond.shuru-network.com/peers/peer0.beyond.shuru-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/beyond.shuru-network.com/peers/peer0.beyond.shuru-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.beyond.shuru-network.com:/var/hyperledger/production
    ports:
      - 9051:7051




 
